//! Document registry records and classification.
//!
//! Models the `document_registry` table, tracking every known document's
//! metadata, classification, dependencies, and content hash.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::hierarchy::Layer;

/// Classification of a document's role in the project.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Classification {
    /// Core project documentation.
    Core,
    /// Architecture and design documentation.
    Architecture,
    /// API or interface documentation.
    Api,
    /// Guide or tutorial content.
    Guide,
    /// Reference material.
    Reference,
    /// Decision record.
    Decision,
    /// Goal or objective tracking.
    Goal,
    /// Progress or status tracking.
    Progress,
    /// Template document.
    Template,
    /// Other / unclassified.
    Other,
}

impl Classification {
    /// Parse a classification string.
    pub fn parse(s: &str) -> Option<Classification> {
        match s.to_lowercase().as_str() {
            "core" => Some(Classification::Core),
            "architecture" => Some(Classification::Architecture),
            "api" => Some(Classification::Api),
            "guide" => Some(Classification::Guide),
            "reference" => Some(Classification::Reference),
            "decision" => Some(Classification::Decision),
            "goal" => Some(Classification::Goal),
            "progress" => Some(Classification::Progress),
            "template" => Some(Classification::Template),
            "other" => Some(Classification::Other),
            _ => None,
        }
    }

    /// Convert to string representation.
    pub fn as_str(&self) -> &'static str {
        match self {
            Classification::Core => "core",
            Classification::Architecture => "architecture",
            Classification::Api => "api",
            Classification::Guide => "guide",
            Classification::Reference => "reference",
            Classification::Decision => "decision",
            Classification::Goal => "goal",
            Classification::Progress => "progress",
            Classification::Template => "template",
            Classification::Other => "other",
        }
    }
}

/// The type of document based on format and structure.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DocumentType {
    /// Markdown document.
    Markdown,
    /// YAML configuration or data file.
    Yaml,
    /// JSON configuration or data file.
    Json,
    /// Plain text.
    PlainText,
    /// Source code with embedded documentation.
    SourceCode,
}

impl DocumentType {
    /// Infer document type from file extension.
    pub fn from_extension(ext: &str) -> DocumentType {
        match ext.to_lowercase().as_str() {
            "md" | "markdown" => DocumentType::Markdown,
            "yml" | "yaml" => DocumentType::Yaml,
            "json" => DocumentType::Json,
            "txt" | "text" => DocumentType::PlainText,
            _ => DocumentType::SourceCode,
        }
    }

    /// Infer document type from filename.
    pub fn from_filename(filename: &str) -> DocumentType {
        match filename.rsplit_once('.') {
            Some((_, ext)) => Self::from_extension(ext),
            None => DocumentType::PlainText,
        }
    }
}

/// Origin of a document (how it was created).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DocumentOrigin {
    /// Generated by PRISM.
    Derived,
    /// Created by a human.
    Authored,
    /// Partially generated, partially edited.
    SemiDerived,
}

/// A record in the document registry, representing a tracked document.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DocumentRecord {
    /// Unique document ID.
    pub id: String,
    /// Path relative to project root.
    pub path: String,
    /// Document title extracted from frontmatter or first heading.
    pub title: Option<String>,
    /// Which layer this document belongs to.
    pub layer: Layer,
    /// Classification of the document's role.
    pub classification: Classification,
    /// Document format type.
    pub document_type: DocumentType,
    /// Origin (derived, authored, semi-derived).
    pub origin: DocumentOrigin,
    /// SHA-256 content hash.
    pub content_hash: String,
    /// When the document was first registered.
    pub created_at: DateTime<Utc>,
    /// When the document was last modified.
    pub updated_at: DateTime<Utc>,
    /// Tags associated with this document.
    pub tags: Vec<String>,
}

/// A dependency relationship between two documents.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DocumentDependency {
    /// ID of the source document (the one that depends).
    pub source_id: String,
    /// ID of the target document (the one depended upon).
    pub target_id: String,
    /// Type of dependency (e.g. "references", "extends", "implements").
    pub dependency_type: String,
}

/// Classify a document based on its path and filename.
#[tracing::instrument(skip_all, fields(path))]
pub fn classify_document(path: &str) -> (Classification, Layer) {
    let layer = crate::hierarchy::classify_path(path);
    let classification = classify_by_path(path);
    (classification, layer)
}

/// Heuristic classification based on path and filename patterns.
fn classify_by_path(path: &str) -> Classification {
    let lower = path.to_lowercase();
    let filename = lower.rsplit('/').next().unwrap_or(&lower);

    // Check filename patterns
    if filename.contains("architecture") || filename.contains("design") {
        return Classification::Architecture;
    }
    if filename.contains("api") || filename.contains("endpoint") {
        return Classification::Api;
    }
    if filename.contains("decision") || filename.contains("adr") {
        return Classification::Decision;
    }
    if filename.contains("goal") || filename.contains("objective") {
        return Classification::Goal;
    }
    if filename.contains("progress")
        || filename.contains("status")
        || filename.contains("changelog")
    {
        return Classification::Progress;
    }
    if filename.contains("guide") || filename.contains("tutorial") || filename.contains("howto") {
        return Classification::Guide;
    }
    if filename.contains("template") {
        return Classification::Template;
    }
    if filename.contains("schema") || filename.contains("reference") || filename.contains("spec") {
        return Classification::Reference;
    }

    // Check directory patterns (handle both "dir/file" and "/dir/file" forms)
    if lower.contains("/refs/")
        || lower.contains("/reference/")
        || lower.starts_with("refs/")
        || lower.starts_with("reference/")
    {
        return Classification::Reference;
    }
    if lower.contains("/decisions/")
        || lower.contains("/adrs/")
        || lower.starts_with("decisions/")
        || lower.starts_with("adrs/")
    {
        return Classification::Decision;
    }

    // CLAUDE.md and CONTEXT.md are core docs
    if filename == "claude.md" || filename == "context.md" {
        return Classification::Core;
    }

    Classification::Other
}

/// Build a dependency graph from a list of dependencies.
///
/// Returns a map from document ID to list of document IDs it depends on.
#[tracing::instrument(skip_all)]
pub fn build_dependency_graph(
    deps: &[DocumentDependency],
) -> std::collections::HashMap<String, Vec<String>> {
    let mut graph: std::collections::HashMap<String, Vec<String>> =
        std::collections::HashMap::new();
    for dep in deps {
        graph
            .entry(dep.source_id.clone())
            .or_default()
            .push(dep.target_id.clone());
    }
    graph
}

/// Find all documents that transitively depend on a given document.
///
/// Useful for cascading staleness: if doc A changes, find all docs that
/// depend on A (directly or indirectly) so they can be marked stale.
#[tracing::instrument(skip(deps), fields(target_id))]
pub fn find_transitive_dependents(target_id: &str, deps: &[DocumentDependency]) -> Vec<String> {
    // Build reverse graph: target → list of sources that depend on it
    let mut reverse_graph: std::collections::HashMap<&str, Vec<&str>> =
        std::collections::HashMap::new();
    for dep in deps {
        reverse_graph
            .entry(dep.target_id.as_str())
            .or_default()
            .push(dep.source_id.as_str());
    }

    let mut visited = std::collections::HashSet::new();
    let mut queue = std::collections::VecDeque::new();
    queue.push_back(target_id);
    visited.insert(target_id);

    let mut dependents = Vec::new();

    while let Some(current) = queue.pop_front() {
        if let Some(sources) = reverse_graph.get(current) {
            for &source in sources {
                if visited.insert(source) {
                    dependents.push(source.to_string());
                    queue.push_back(source);
                }
            }
        }
    }

    dependents
}
